easy_admin:
   entities:
       # List the entity class name you want to manage
       
       - App\Entity\Categorie
       - App\Entity\Quiz
       - App\Entity\Question
       - App\Entity\Reponses
       - App\Entity\User
