<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerM7xnXJA\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerM7xnXJA/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerM7xnXJA.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerM7xnXJA\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerM7xnXJA\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'M7xnXJA',
    'container.build_id' => '9abd4ef2',
    'container.build_time' => 1558954626,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerM7xnXJA');
